name: GitHub Actions CI
run-name: Deploy javadocs and run tests.
on: [push]
jobs:
  Deploy-Docs:
    name: Deploy javadocs.
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Install a compatible Java environment to GitHub's virtual machine.
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 25
      - name: Clone this repository to GitHub's virtual machine.
        uses: actions/checkout@v6
      - name: Build the javadocs on GitHub's virtual machine.
        run: javadoc -d docs -sourcepath src adt
      - name: Deploy the docs directory on GitHub's virtual machine to this repository's gh-pages branch.
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: docs
          branch: gh-pages